image: nikolaik/python-nodejs:python3.10-nodejs17-bullseye

stages:
  - pre_check
  - version
  - publish
  - push
  - setup
  - compile

pre_check:
  stage: pre_check
  image: alpine:3.15.0
  script:
    - echo "Branch names have to be started with bugfix/, feature/ or break/" >> /dev/stderr
    - exit 1
  except:
    - develop
    - /^bugfix/
    - /^feature/
    - /^break/

setup:
  stage: setup
  needs:
  - pre_check
  script:
    - yarn install --frozen-lockfile
  artifacts:
    paths:
      - node_modules/
      - packages/**/node_modules/

compile:
  stage: compile
  needs:
    - setup
  script:
    - yarn compile
  artifacts:
    paths:
      - packages/**/dist/

version:
  stage: version
  needs: 
    - pre_check
  script:
    - git checkout $CI_COMMIT_BRANCH
    - git config user.name "GitLab CI/CD"
    - git config user.email "gitlab@codeloves.me"
    - git remote show origin
    - git remote set-url --push origin git@gitlab:$CI_PROJECT_PATH
    - git remote show origin
    - git push --follow-tags origin HEAD:$CI_COMMIT_REF_NAME
    - if [[ $CI_COMMIT_MESSAGE == "Merge branch 'bugfix/"* ]]; then yarn versionPatch; fi
    - if [[ $CI_COMMIT_MESSAGE == "Merge branch 'feature/"* ]]; then yarn versionMinor; fi
    - if [[ $CI_COMMIT_MESSAGE == "Merge branch 'break/"* ]]; then yarn versionMajor; fi
  only:
    - develop

github:
  stage: push
  needs:
    - pre_check
  script: 
    - git restore .
    - git checkout $CI_COMMIT_BRANCH
    - git push --follow-tags https://$GITLAB_USER_LOGIN:$GITHUB_TOKEN@github.com/$GITLAB_USER_LOGIN/$CI_PROJECT_NAME.git $CI_COMMIT_BRANCH
  only:
    - tags


npm:
  stage: publish
  needs:
    - pre_check
  script:
    - echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" >> .npmrc
    - git restore .
    - npm run publish
  only:
    - tags