image: nikolaik/python-nodejs:python3.10-nodejs17-bullseye

stages:
  - setup
  - compile
  - publish
  - push

setup:
  stage: setup
  script:
    - yarn install --frozen-lockfile
  artifacts:
    paths:
      - node_modules/
      - packages/**/node_modules/

compile:
  stage: compile
  needs:
    - setup
  script:
    - yarn compile
  artifacts:
    paths:
      - packages/**/dist/

npm:
  stage: publish
  needs:
    - setup
    - compile
  script:
    - echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" >> .npmrc
    - git restore .
    - npm run publish
  only:
    - tags

github:
  stage: push
  needs: []
  script: 
    - git restore .
    - git checkout $CI_COMMIT_BRANCH
    - git push https://$GITLAB_USER_LOGIN:$GITHUB_TOKEN@github.com/$GITLAB_USER_LOGIN/$CI_PROJECT_NAME.git $CI_COMMIT_BRANCH
  only:
    - develop
    - master
