image: nikolaik/python-nodejs:python3.6-nodejs16-stretch

stages:
    - publish

publish:
    stage: publish
    script:
        - npm i -g lerna
        - yarn
        - yarn compile
        - echo "@codelovesme:registry=http://codeloves.me:2800/api/v4/projects/4/packages/npm/">.npmrc
        - echo "//codeloves.me:2800/api/v4/packages/npm/:_authToken=${CI_JOB_TOKEN}">>.npmrc
        - echo "//codeloves.me:2800/api/v4/projects/${CI_PROJECT_ID}/packages/npm/:_authToken=${CI_JOB_TOKEN}">>.npmrc
        - lerna publish from-package -y
    # only:
    #     - tags
