# variables needed in pipeline environment
# GITHUB_TOKEN          token to authenticate the pipeline pushing commits to github.com
# BITBUCKET_TOKEN       token to authenticate the pipeline pushing commits to bitbucket.org
# PERSONAL_ACCESS_TOKEN token to authenticate as gitlab@codeloves.me who is authorized to do automated operations like versioning, merge, etc...

image: nikolaik/python-nodejs:python3.10-nodejs17-bullseye

stages:
  - pre_check
  - setup
  - compile
  - version
  - publish
  - push

variables:
  GITHUB_URL: https://gitlab-codelovesme:$GITHUB_TOKEN@github.com/codelovesme/$CI_PROJECT_NAME.git
  BITBUCKET_URL: https://gitlab-codelovesme:$BITBUCKET_TOKEN@bitbucket.org/codelovesme/$CI_PROJECT_NAME.git

pre_check:
  stage: pre_check
  image: alpine:3.15.0
  script:
    - echo -e "\033[31m Branch names have to be started with bugfix/, feature/ or break/"
    - exit 1
  except:
    - develop
    - tags
    - /^bugfix/
    - /^feature/
    - /^break/

setup:
  stage: setup
  script:
    - yarn install --frozen-lockfile
  artifacts:
    paths:
      - node_modules/
      - packages/**/node_modules/
  only:
    - tags
    - /^bugfix/
    - /^feature/
    - /^break/

compile:
  stage: compile
  needs:
    - setup
  script:
    - yarn compile
  artifacts:
    paths:
      - packages/**/dist/
  only:
    - tags
    - /^bugfix/
    - /^feature/
    - /^break/

npm:
  stage: publish
  needs:
    - setup
    - compile
  script:
    - echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" >> .npmrc
    - git restore .
    - yarn publishNPM
  only:
    - tags

version:
  stage: version
  script:
    - git checkout $CI_COMMIT_BRANCH
    - git config user.name "GitLab CI/CD"
    - git config user.email "gitlab@codeloves.me"
    - url_host=`git remote get-url origin | sed -e "s/https:\/\/gitlab-ci-token:.*@//g"`
    - git remote set-url origin "https://$GITLAB_USER_LOGIN:$PERSONAL_ACCESS_TOKEN@${url_host}"
    - if [[ $CI_COMMIT_MESSAGE == "Merge branch 'bugfix/"* ]]; then yarn versionPatch
    - elif [[ $CI_COMMIT_MESSAGE == "Merge branch 'feature/"* ]]; then yarn versionMinor
    - elif [[ $CI_COMMIT_MESSAGE == "Merge branch 'break/"* ]]; then yarn versionMajor; fi
  only:
    - develop

.push:
  stage: push
  needs: []
  script: 
    - git restore .;
    - git push $HOST ${CI_COMMIT_TAG:-HEAD:refs/heads/$CI_COMMIT_BRANCH};
  only:
    variables:
      - $CI_COMMIT_BRANCH == "master"
      - $CI_COMMIT_BRANCH == "develop"
      - $CI_COMMIT_TAG =~ /^v/

github_push:
  extends: .push
  variables:
    HOST: $GITHUB_URL

bitbucket_push:
  extends: .push
  variables:
    HOST: $BITBUCKET_URL
