image: nikolaik/python-nodejs:python3.6-nodejs16-stretch

stages:
    - publish

publish:
    stage: publish
    script:
        - npm i -g lerna
        - yarn
        - yarn compile
        - cd packages/core
        - echo "//codeloves.me:2800/api/v4/projects/${CI_PROJECT_ID}/packages/npm/:_authToken=${CI_JOB_TOKEN}">.npmrc
        - npm publish
    only:
        - tags
