image: nikolaik/python-nodejs:python3.10-nodejs17-bullseye

stages:
  - pre_check
  - version
  - publish
  - push
  - setup
  - compile

pre_check:
  stage: pre_check
  image: alpine:3.15.0
  script:
    - echo -e "\033[31m Branch names have to be started with bugfix/, feature/ or break/"
    - exit 1
  except:
    - develop
    - tags
    - /^bugfix/
    - /^feature/
    - /^break/

setup:
  stage: setup
  script:
    - yarn install --frozen-lockfile
  artifacts:
    paths:
      - node_modules/
      - packages/**/node_modules/
  only:
    - /^bugfix/
    - /^feature/
    - /^break/

compile:
  stage: compile
  needs:
    - setup
  script:
    - yarn compile
  artifacts:
    paths:
      - packages/**/dist/
  only:
    - /^bugfix/
    - /^feature/
    - /^break/

version:
  stage: version
  needs: 
    - pre_check
  script:
    - git checkout $CI_COMMIT_BRANCH
    - git config user.name "GitLab CI/CD"
    - git config user.email "gitlab@codeloves.me"
    - url_host=`git remote get-url origin | sed -e "s/https:\/\/gitlab-ci-token:.*@//g"`
    - git remote set-url origin "https://$GITLAB_USER_LOGIN:$PERSONAL_ACCESS_TOKEN@${url_host}"
    - if [[ $CI_COMMIT_MESSAGE == "Merge branch 'bugfix/"* ]]; then yarn versionPatch; fi
    - if [[ $CI_COMMIT_MESSAGE == "Merge branch 'feature/"* ]]; then yarn versionMinor; fi
    - if [[ $CI_COMMIT_MESSAGE == "Merge branch 'break/"* ]]; then yarn versionMajor; fi



github:
  stage: push
  script: 
    - git restore .
    - git checkout $CI_COMMIT_BRANCH
    - git push --follow-tags https://$GITLAB_USER_LOGIN:$GITHUB_TOKEN@github.com/$GITLAB_USER_LOGIN/$CI_PROJECT_NAME.git $CI_COMMIT_BRANCH
  only:
    - tags


npm:
  stage: publish
  script:
    - echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" >> .npmrc
    - git restore .
    - npm run publish
  only:
    - tags