image: nikolaik/python-nodejs:python3.6-nodejs16-stretch

stages:
    - setup
    - compile
    - publish

setup:
    stage: setup
    script:
        - npm i -g lerna
        - yarn

compile:
    stage: compile
    dependencies:
        - setup
    script:
        - yarn compile

publish:
    stage: publish
    dependencies:
        - compile
    script:
        - npm publish
    only:
        - tags
