image: nikolaik/python-nodejs:python3.6-nodejs16-stretch

stages:
  - setup
  - compile
  - publish

setup:
  stage: setup
  script:
    - yarn
  artifacts:
    paths:
      - node_modules/
      - packages/**/node_modules/

compile:
  stage: compile
  dependencies:
    - setup
  script:
    - yarn compile
  artifacts:
    paths:
      - packages/**/dist/

publish:
  stage: publish
  dependencies:
    - setup
    - compile
  script:
    - echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" >> .npmrc
    - git status
    - npm run publish

