image: nikolaik/python-nodejs:python3.6-nodejs16-stretch

stages:
    - publish

publish:
    stage: publish
    script:
        - npm i -g lerna
        - yarn
        - yarn compile
        - lerna publish from-package -y
    # only:
    #     - tags
