image: nikolaik/python-nodejs:python3.6-nodejs16-alpine

stages:
    - publish

publish:
    stage: publish
    script:
        - apk install g++ gcc make
        - npm i -g lerna
        - yarn
        - yarn compile:prod
        - echo "//codeloves.me:2800/api/v4/projects/${CI_PROJECT_ID}/packages/npm/:_authToken=${CI_JOB_TOKEN}">.npmrc
        - lerna publish
    # only:
    #     - tags
