import { Interaction } from "./interaction.h";
import { Particle } from "../../particle";

type AssertInteraction<T extends Interaction> = T;

export type Result = [
    AssertInteraction<[Particle]>,
    AssertInteraction<[Particle, Particle]>,
    AssertInteraction<[Particle, Particle, Particle]>,
    AssertInteraction<[Particle] | [Particle]>,
    AssertInteraction<[Particle] | [Particle, Particle]>,
    AssertInteraction<[Particle] | [Particle, Particle, Particle]>,
    AssertInteraction<[Particle, Particle] | [Particle]>,
    AssertInteraction<[Particle, Particle] | [Particle, Particle]>,
    AssertInteraction<[Particle, Particle] | [Particle, Particle, Particle]>,
    AssertInteraction<[Particle, Particle, Particle] | [Particle]>,
    AssertInteraction<[Particle, Particle, Particle] | [Particle, Particle]>,
    AssertInteraction<[Particle, Particle, Particle] | [Particle, Particle, Particle]>,
    AssertInteraction<[Particle] | [Particle] | [Particle]>,
    AssertInteraction<[Particle] | [Particle] | [Particle, Particle]>,
    AssertInteraction<[Particle] | [Particle] | [Particle, Particle, Particle]>,
    AssertInteraction<[Particle, Particle] | [Particle] | [Particle]>,
    AssertInteraction<[Particle, Particle] | [Particle] | [Particle, Particle]>,
    AssertInteraction<[Particle, Particle] | [Particle] | [Particle, Particle, Particle]>,
    AssertInteraction<[Particle, Particle, Particle] | [Particle] | [Particle]>,
    AssertInteraction<[Particle, Particle, Particle] | [Particle] | [Particle, Particle]>,
    AssertInteraction<[Particle, Particle, Particle] | [Particle] | [Particle, Particle, Particle]>,
    AssertInteraction<[Particle, Particle, Particle] | [Particle, Particle] | [Particle]>,
    AssertInteraction<[Particle, Particle, Particle] | [Particle, Particle] | [Particle, Particle]>,
    AssertInteraction<[Particle, Particle, Particle] | [Particle, Particle] | [Particle, Particle, Particle]>,
    AssertInteraction<[Particle, Particle, Particle] | [Particle, Particle, Particle] | [Particle]>,
    AssertInteraction<[Particle, Particle, Particle] | [Particle, Particle, Particle] | [Particle, Particle]>,
    AssertInteraction<[Particle, Particle, Particle] | [Particle, Particle, Particle] | [Particle, Particle, Particle]>,
    AssertInteraction<[Particle<"abc">]>,
    AssertInteraction<[Particle, Particle<"vbvb">]>,
    AssertInteraction<[Particle, Particle<"vbc">, Particle]>,
    AssertInteraction<[Particle] | [Particle<"gfgfgfgfg">]>,
    AssertInteraction<[Particle] | [Particle, Particle<"dfdfd", { a: 23 }>]>,
    AssertInteraction<[Particle] | [Particle, Particle, Particle<"sdsdsd", boolean, { version: string }>]>,
    AssertInteraction<[Particle, Particle] | [Particle]>,
    AssertInteraction<[Particle, Particle] | [Particle, Particle]>,
    AssertInteraction<[Particle, Particle] | [Particle, Particle, Particle]>,
    AssertInteraction<[Particle, Particle, Particle] | [Particle]>,
    AssertInteraction<[Particle, Particle, Particle] | [Particle, Particle]>,
    AssertInteraction<[Particle, Particle, Particle] | [Particle, Particle, Particle]>,
    AssertInteraction<[Particle] | [Particle] | [Particle]>,
    AssertInteraction<[Particle] | [Particle] | [Particle, Particle]>,
    AssertInteraction<[Particle] | [Particle] | [Particle, Particle, Particle]>,
    AssertInteraction<[Particle, Particle] | [Particle] | [Particle]>,
    AssertInteraction<[Particle, Particle] | [Particle] | [Particle, Particle]>,
    AssertInteraction<[Particle, Particle] | [Particle] | [Particle, Particle, Particle]>,
    AssertInteraction<[Particle, Particle, Particle] | [Particle] | [Particle]>,
    AssertInteraction<
        [Particle, Particle, Particle] | [Particle] | [Particle, Particle<"mmn", {}, { version: string }>]
    >,
    AssertInteraction<[Particle, Particle, Particle] | [Particle] | [Particle, Particle, Particle]>,
    AssertInteraction<[Particle, Particle, Particle] | [Particle, Particle] | [Particle]>,
    AssertInteraction<[Particle, Particle, Particle] | [Particle, Particle] | [Particle, Particle]>,
    AssertInteraction<[Particle, Particle, Particle] | [Particle, Particle] | [Particle, Particle, Particle]>,
    AssertInteraction<[Particle, Particle, Particle] | [Particle, Particle, Particle] | [Particle]>,
    AssertInteraction<[Particle, Particle, Particle] | [Particle, Particle, Particle] | [Particle, Particle]>,
    AssertInteraction<[Particle, Particle, Particle] | [Particle, Particle, Particle] | [Particle, Particle, Particle]>
];
