const disallowedWordsInEuglenaName: string[] = [
    "123456",
    "abc123",
    "admin",
    "administrator",
    "adult",
    "alcohol",
    "alert",
    "amazon",
    "anarchy",
    "anonymizer",
    "anonymous",
    "antisocial",
    "apple",
    "attack",
    "badass",
    "bastard",
    "beer",
    "bet",
    "betrayer",
    "bitch",
    "blackhat",
    "blood",
    "blunt",
    "bomb",
    "bot",
    "bully",
    "cannabis",
    "cash",
    "casino",
    "chaos",
    "cheater",
    "chronic",
    "clown",
    "cocaine",
    "contact",
    "corrupt",
    "crack",
    "crime",
    "criminal",
    "crossfire",
    "cruel",
    "cyanide",
    "danger",
    "deadly",
    "death",
    "deceiver",
    "destroy",
    "devil",
    "disaster",
    "disrupt",
    "dope",
    "drugs",
    "dumbass",
    "ecstasy",
    "escort",
    "evil",
    "exploit",
    "facebook",
    "fraud",
    "gamble",
    "gangster",
    "ghetto",
    "gloryhole",
    "google",
    "gore",
    "greed",
    "gun",
    "hacker",
    "hate",
    "hazard",
    "hell",
    "heroin",
    "high",
    "hitman",
    "homicide",
    "hostage",
    "illegal",
    "infect",
    "injury",
    "insane",
    "insult",
    "instagram",
    "intimidate",
    "isis",
    "jerk",
    "kill",
    "knife",
    "knockout",
    "liar",
    "linkedin",
    "loan",
    "loser",
    "lottery",
    "lunatic",
    "mafia",
    "malware",
    "massacre",
    "meds",
    "meth",
    "misery",
    "money",
    "monster",
    "mugshot",
    "murder",
    "nazi",
    "ninja",
    "nude",
    "obscene",
    "offense",
    "overdose",
    "pain",
    "panic",
    "parasite",
    "pharma",
    "phishing",
    "pill",
    "poison",
    "porn",
    "pot",
    "prison",
    "psycho",
    "racist",
    "rape",
    "revenge",
    "riot",
    "robber",
    "rotten",
    "rum",
    "scam",
    "scumbag",
    "seduce",
    "sex",
    "shoot",
    "sick",
    "sin",
    "skull",
    "slayer",
    "sleazy",
    "slut",
    "smuggle",
    "sniper",
    "spam",
    "stab",
    "stoned",
    "stupid",
    "suicide",
    "survive",
    "sword",
    "terrorism",
    "terrorist",
    "threat",
    "toxic",
    "tragedy",
    "trauma",
    "twitter",
    "ugly",
    "underworld",
    "unholy",
    "unlawful",
    "unsafe",
    "vandal",
    "vicious",
    "violate",
    "violence",
    "virus",
    "vulgar",
    "wannabe",
    "weapon",
    "weed",
    "weirdo",
    "wicked",
    "wild",
    "witch",
    "worm",
    "wound",
    "xxx",
    "yakuza",
    "yahoo",
    "youtube",
    "zealot",
    // Add more words as needed
];


export function validateUsernameCharacters(username: string): boolean {
    const regex = /^[a-zA-Z0-9]{4,20}$/;
    return regex.test(username);
}

export function validateUsernameDisallowedList(username: string): boolean {
    const lowerCaseUsername = username.toLowerCase();
    return !disallowedWordsInEuglenaName.some(word => lowerCaseUsername.includes(word));
}


/**
 * Minimum length of 8 characters
* At least one uppercase letter
* At least one lowercase letter
* At least one digit
* Optional: Special characters (e.g., !@#$%^&*)
 */
export function validatePassword(password: string): boolean {
    const regex = /^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*[@$!%*?&])[A-Za-z\d@$!%*?&]{8,}$/;
    return regex.test(password);
}

