//! `euglena doctor` — one command answering what this migration made
//! invisible: which `code` was picked and how, whether this is a real
//! project, whether every declared organelle is installed, and whether
//! `main.code` is ours to regenerate. Every failing line names its fix.

use std::fs;
use std::path::{Path, PathBuf};
use std::process;

use crate::exec::{self, CodeDiscovery, MIN_CODE_VERSION};
use crate::{codegen, config, invocation, manifest};

pub fn run() {
    let mut ok = true;
    let project_root = std::env::current_dir().unwrap_or_else(|_| PathBuf::from("."));

    println!("Code interpreter:");
    check_code_binary(&mut ok);

    println!();
    println!("Project ({}):", project_root.display());
    check_project(&project_root, &mut ok);

    if ok {
        println!();
        println!("Everything checks out.");
    } else {
        println!();
        println!("Some checks failed — see above.");
        process::exit(1);
    }
}

fn check_code_binary(ok: &mut bool) {
    match config::read_code_binary_path() {
        Some(path) => match exec::code_interpreter_version(&path) {
            Some(v) if v >= MIN_CODE_VERSION => {
                println!(
                    "  configured: {} (v{})",
                    path.display(),
                    exec::fmt_version(v)
                );
            }
            Some(v) => {
                println!(
                    "  configured: {} (v{} — below the required v{})",
                    path.display(),
                    exec::fmt_version(v),
                    exec::fmt_version(MIN_CODE_VERSION)
                );
                *ok = false;
            }
            None => {
                println!(
                    "  configured: {} (does not respond to --version — broken?)",
                    path.display()
                );
                *ok = false;
            }
        },
        None => match exec::discover_cdlvsm_code_on_path() {
            Some(CodeDiscovery::Ready(p)) => println!("  discovered on PATH: {p}"),
            Some(CodeDiscovery::TooOld { path, version }) => {
                println!(
                    "  found on PATH but too old: {path} (v{}, need v{})",
                    exec::fmt_version(version),
                    exec::fmt_version(MIN_CODE_VERSION)
                );
                println!("    fix: cdlvsm install code");
                *ok = false;
            }
            None => {
                println!("  none found");
                println!("    fix: cdlvsm install code");
                *ok = false;
            }
        },
    }
}

fn check_project(project_root: &Path, ok: &mut bool) {
    if project_root.join(".code").is_dir() {
        println!("  .code/ marker: present");
    } else {
        println!("  .code/ marker: MISSING — not a code project root");
        println!(
            "    fix: {} init, or `code init` here",
            invocation::command_prefix()
        );
        *ok = false;
    }

    let manifest_path = project_root.join("manifest.json");
    if !manifest_path.is_file() {
        println!("  manifest.json: none (plain code project, not an euglena app)");
        return;
    }

    match manifest::parse_manifest(&manifest_path) {
        Ok(app_manifest) => {
            println!(
                "  manifest.json: parses ({} organelle(s))",
                app_manifest.organelles.len()
            );
            for (alias, entry) in &app_manifest.organelles {
                let reference = entry.reference();
                match codegen::organelle_link_target(project_root, reference) {
                    Ok(target) => println!("    {alias} -> {reference} [{target}]"),
                    Err(e) => {
                        println!("    {alias} -> {reference} [MISSING]");
                        println!("      {e}");
                        *ok = false;
                    }
                }
            }
        }
        Err(e) => {
            println!("  manifest.json: {e}");
            *ok = false;
        }
    }

    let entry_path = project_root.join("main.code");
    if entry_path.is_file() {
        let text = fs::read_to_string(&entry_path).unwrap_or_default();
        if text.starts_with(codegen::GENERATED_HEADER) {
            println!("  main.code: generated by euglena (regenerated on every run/build/test)");
        } else {
            println!("  main.code: hand-written — euglena will refuse to regenerate it");
        }
    } else {
        println!("  main.code: none yet (generated on first run/build/test)");
    }
}
